# Licensed under The Unlicense
# Feel free to reuse, edit and redistribute this workflow as you wish, no credits needed
# See https://github.com/lowlighter/metrics for documentation about how to use metrics action

name: Metrics
on:
  # 🌏 Think about the planet! No need to update stats too frequently
  schedule: [{cron: "0 * * * *"}]
  # 💡 The following line lets you run workflow manually from the action tab!
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:

      - name: General Section
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: general.svg
          output_action: gist
          committer_gist: 4d433b19f884c9c188360f4390d9e650
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: crmacca
          template: classic
          base: header, activity, community, repositories
          config_octicon: yes
          config_timezone: Australia/Sydney
          config_twemoji: yes
          plugin_activity: yes
          plugin_activity_days: 60
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          plugin_code: yes
          plugin_code_days: 3
          plugin_code_lines: 12
          plugin_code_load: 400
          plugin_code_visibility: public
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_notable: yes
          plugin_notable_filter: starts:>50 forks:>50
          plugin_notable_from: organization
          plugin_notable_types: commit
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_lines: yes
          plugin_lines_history_limit: 3
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          
      - name: Achievement Section
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: achievements.svg
          output_action: gist
          committer_gist: 4d433b19f884c9c188360f4390d9e650
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: crmacca
          template: classic
          base: ""
          base_skip: yes
          config_order: github.notable, github.achievements
          config_timezone: Australia/Sydney
          config_twemoji: yes
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_notable: yes
          plugin_notable_filter: stars:>50 forks:>50
          plugin_notable_from: organization
          plugin_notable_types: commit
          
      - name: Languages Section
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: languages.svg
          output_action: gist
          committer_gist: 4d433b19f884c9c188360f4390d9e650
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: crmacca
          template: classic
          base: ""
          base_skip: yes
          config_timezone: Australia/Sydney
          config_twemoji: yes
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          
      - name: Social Section
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: social.svg
          output_action: gist
          committer_gist: 4d433b19f884c9c188360f4390d9e650
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: crmacca
          template: classic
          base: ""
          base_skip: yes
          config_display: large
          config_timezone: Australia/Sydney
          plugin_16personalities: yes
          plugin_16personalities_scores: yes
          plugin_16personalities_sections: personality, profile, traits
          plugin_16personalities_url: https://www.16personalities.com/profiles/77ae30e239dce
          plugin_steam: yes
          plugin_steam_achievements_limit: 2
          plugin_steam_games_limit: 1
          plugin_steam_playtime_threshold: 2
          plugin_steam_recent_games_limit: 1
          plugin_steam_sections: player, most-played, recently-played
          plugin_steam_user: IAmNotAMonkey
          
